#!/usr/bin/env python3
"""Rebuild system/INDEX.tsv (generated, never authoritative)."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from brainlib import ROOT, iter_artifacts

COLS = ["id", "path", "artifact_type", "domain", "status", "sensitivity",
        "topics", "entities", "title", "created_at"]


def main():
    rows = []
    for rel, fm, _ in iter_artifacts():
        rows.append([
            fm.get("id", ""), rel, fm.get("artifact_type", ""), fm.get("domain", ""),
            str(fm.get("status", "")), fm.get("sensitivity", "personal") or "personal",
            ",".join(fm.get("topics", []) if isinstance(fm.get("topics"), list) else []),
            ",".join(fm.get("entities", []) if isinstance(fm.get("entities"), list) else []),
            str(fm.get("title", "")).replace("\t", " "), str(fm.get("created_at", "")),
        ])
    out = os.path.join(ROOT, "system", "INDEX.tsv")
    with open(out, "w", encoding="utf-8") as f:
        f.write("# GENERATED by tools/build_index.py — rebuildable, never authoritative\n")
        f.write("\t".join(COLS) + "\n")
        for r in sorted(rows, key=lambda r: r[0]):
            f.write("\t".join(r) + "\n")
    print(f"indexed {len(rows)} artifacts -> system/INDEX.tsv")


if __name__ == "__main__":
    main()
