#!/usr/bin/env python3
"""Regenerate BRAIN_MAP.md — a one-page generated map of the repo."""
import os, sys, datetime
from collections import Counter
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from brainlib import ROOT, iter_artifacts, now_pt

DESC = {
    "queue": "shared research queue (one file per task; QUEUE.md is the dashboard)",
    "timeline": "raw dated observations (never auto-promoted to facts)",
    "domains": "expandable domain folders (DOMAIN_PROFILE.md each)",
    "newspaper": "editions, drafts, annotations, questions for Brendan",
    "preferences": "confirmed/proposed/rejected rules + interest profile",
    "predictions": "dated predictions with confidence and horizon",
    "outcomes": "scored results of predictions",
    "decisions": "decision records", "people": "people notes", "projects": "project notes",
    "sources": "source registry and reliability tracking",
    "agents": "agent role registry", "skills": "skill registry (canonical skills in .claude/skills)",
    "system": "policies, schemas, manifest, operations, audits, health",
    "tools": "stdlib Python tools (validate, index, search, queue, newspaper, annotations)",
    "tests": "stress tests, evaluations, synthetic fixtures",
    "docs": "architecture, operations, daily guide, limitations",
}


def main():
    by_type, by_domain = Counter(), Counter()
    n = 0
    for rel, fm, _ in iter_artifacts():
        n += 1
        by_type[fm.get("artifact_type", "?")] += 1
        by_domain[fm.get("domain", "-")] += 1
    now = now_pt().strftime("%Y-%m-%d %H:%M")
    lines = ["<!-- GENERATED by tools/build_brain_map.py — do not hand-edit -->",
             f"# Brain Map — {now}", "",
             "Start here: `CLAUDE.md` (contract) → `CURRENT_PRIORITIES.md` → your domain.", "",
             "## Layout"]
    for d in sorted(DESC):
        if os.path.isdir(os.path.join(ROOT, d)):
            lines.append(f"- `{d}/` — {DESC[d]}")
    lines += ["", f"## Contents ({n} artifacts)",
              "By type: " + ", ".join(f"{k} {v}" for k, v in sorted(by_type.items())),
              "By domain: " + ", ".join(f"{k} {v}" for k, v in sorted(by_domain.items())), "",
              "Rebuild: `python3 tools/build_brain_map.py && python3 tools/build_index.py "
              "&& python3 tools/build_queue_dashboard.py`"]
    open(os.path.join(ROOT, "BRAIN_MAP.md"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"BRAIN_MAP.md rebuilt ({n} artifacts)")


if __name__ == "__main__":
    main()
