#!/usr/bin/env python3
"""Regenerate QUEUE.md from queue/**/task files. Flags folder/status mismatches."""
import os, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from brainlib import ROOT, iter_artifacts, FOLDER_STATUS

ORDER = ["waiting_for_brendan", "active", "continuing_with_assumption", "verification",
         "ready_for_publication", "inbox", "triaged", "scheduled", "watching",
         "published", "completed", "failed", "cancelled"]


def main():
    tasks, warnings = [], []
    for rel, fm, body in iter_artifacts():
        if fm.get("artifact_type") not in ("task", "watch") or not rel.startswith("queue" + os.sep):
            continue
        parts = rel.split(os.sep)
        folder, st = parts[1], str(fm.get("status", ""))
        if folder in FOLDER_STATUS and st not in FOLDER_STATUS[folder]:
            warnings.append(f"- ⚠️ `{rel}`: status `{st}` but lives in `queue/{folder}/`")
        nq = body.count("kind: blocking") + body.count("(blocking)")
        tasks.append((st, fm, rel, nq))
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = ["<!-- GENERATED by tools/build_queue_dashboard.py — do not hand-edit -->",
             f"# Queue Dashboard — {now}", ""]
    if warnings:
        lines += ["## ⚠️ Consistency warnings", *warnings, ""]
    open_ct = sum(1 for st, *_ in tasks if st not in ("completed", "failed", "cancelled", "published"))
    lines.append(f"**{len(tasks)} tasks total, {open_ct} open.**\n")
    for st in ORDER:
        group = [t for t in tasks if t[0] == st]
        if not group:
            continue
        lines.append(f"## {st} ({len(group)})")
        for _, fm, rel, nq in sorted(group, key=lambda t: (str(t[1].get('deadline', '9999')),
                                                           str(t[1].get('created_at', '')))):
            dl = f" ⏰{fm.get('deadline')}" if fm.get("deadline") else ""
            urg = str(fm.get("urgency", ""))
            urg = f" 🔥{urg}" if urg in ("high", "urgent") else ""
            qm = " ❓blocking-question" if nq else ""
            lines.append(f"- [`{fm.get('id')}`]({rel.replace(os.sep, '/')}) — "
                         f"{fm.get('title')} ({fm.get('domain')}{dl}{urg}{qm})")
        lines.append("")
    out = os.path.join(ROOT, "QUEUE.md")
    open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"QUEUE.md rebuilt: {len(tasks)} tasks, {len(warnings)} warnings")
    sys.exit(2 if warnings else 0)


if __name__ == "__main__":
    main()
