#!/usr/bin/env bash
# Sync canonical Brendan OS skills from brendan_brain to specialist repos.
# Canonical source: brendan_brain/.claude/skills/. Synced skills per repo: brain-sync, brain-ops.
# Usage: tools/sync_skills.sh [--check]   (--check verifies checksums without copying)
set -euo pipefail
BRAIN="$(cd "$(dirname "$0")/.." && pwd)"
PARENT="$(dirname "$BRAIN")"
REPOS=(operator-notebook FootyBot health-notebook trading-notebook)
SKILLS=(brain-sync brain-ops)
MODE="${1:-sync}"
MANIFEST="$BRAIN/skills/sync_manifest.tsv"

checksum() { sha256sum "$1" | cut -d' ' -f1; }

status=0
[ "$MODE" = "--check" ] || : > "$MANIFEST.tmp"
for repo in "${REPOS[@]}"; do
  dest_root="$PARENT/$repo"
  if [ ! -d "$dest_root/.git" ]; then
    echo "SKIP $repo (not cloned in this session)"; continue
  fi
  for skill in "${SKILLS[@]}"; do
    src="$BRAIN/.claude/skills/$skill/SKILL.md"
    dest="$dest_root/.claude/skills/$skill/SKILL.md"
    if [ "$MODE" = "--check" ]; then
      if [ ! -f "$dest" ]; then echo "MISSING $repo/$skill"; status=1
      elif [ "$(checksum "$src")" != "$(checksum "$dest")" ]; then
        echo "DIVERGED $repo/$skill (re-run tools/sync_skills.sh)"; status=1
      else echo "OK $repo/$skill"; fi
    else
      mkdir -p "$(dirname "$dest")"
      cp "$src" "$dest"
      echo -e "$repo\t$skill\t$(checksum "$src")\t$(date -I)" >> "$MANIFEST.tmp"
      echo "SYNCED $repo/$skill"
    fi
  done
done
if [ "$MODE" != "--check" ]; then
  { echo -e "# GENERATED by tools/sync_skills.sh — repo\tskill\tsha256\tdate"; cat "$MANIFEST.tmp"; } > "$MANIFEST"
  rm -f "$MANIFEST.tmp"
  echo "manifest: skills/sync_manifest.tsv (commit each repo separately; pushes are NOT atomic — use tools/oplog.py)"
fi
exit $status
